version: "3"

services:
  node-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=dev
      - PORT=3000

    